language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      env: PATH=/usr/local/bin:/usr/bin:/usr/sbin:/bin:/opt/X11/bin

script:
  - ./install

before_cache:
- rm -f $HOME/.cache/pip/log/debug.log

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/Library/Caches/Homebrew"