language: shell

os: osx
osx_image: xcode11.3
env: PATH=/usr/local/bin:/usr/bin:/usr/sbin:/bin:/opt/X11/bin \
           ROS_DISTRO=melodic \
           ROS_CONFIGURATION=desktop_full

script:
- ./install
- ./test

before_cache:
- brew cleanup

cache:
  directories:
  - "/usr/local/Homebrew"
  - "$HOME/Library/Caches/pip"
  - "$HOME/Library/Caches/Homebrew"

before_deploy:
- tar zcf ros-${ROS_DISTRO}-${ROS_CONFIGURATION}.tar.gz -C /usr/local/opt ros

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: ros-${ROS_DISTRO}-${ROS_CONFIGURATION}.tar.gz
  on:
    repo: hguandl/ros-install-osx
    tags: true
